### ISSUE TITLE
Load background-image only for required viewport

### ISSUE THREAD

**Issue by rossmc** [magento/magento2-page-builder#498]
### Description (*)
Currently when background images are added to a page/block with PageBuilder, both mobile and desktop images are loaded on mobile.  On desktop, only desktop images are loaded.
![Screenshot 2020-05-20 at 11 59 31](https://user-images.githubusercontent.com/2452991/82434249-e10f4b00-9a92-11ea-955a-5c4d3dc1bb38.png)

![Screenshot 2020-05-20 at 12 03 07](https://user-images.githubusercontent.com/2452991/82433586-f0da5f80-9a91-11ea-81b5-2727bd6ce826.png)

### Expected behavior (*)
Only the background image for the required viewport should be loaded on the page.
This can be achiveded by wrapping each CSS rule for these background images in a media-query.
Example...
```css
@media only screen and (max-width: 767px) {
    .background-image-5ec4ff47dc153 {
        background-image: url(https://example.com/pub/media/wysiwyg/mens/mens-pants.jpg);
    }
}
@media all and (min-width: 768px) {
    .background-image-5ec4ff47dc153 {
        background-image: url(https://example.com/pub/media/wysiwyg/mens/mens-main.jpg);
    }
}
```

For more info see this blog post:    
https://timkadlec.com/2012/04/media-query-asset-downloading-results/#test5

### Benefits
Images are the biggest cause for slowing down websites, this will help improve this for Magento.
